version: "3"
services:
  app:
    env_file:
      - .env
    restart: always
    depends_on:
      - mysql1
    build: .
    ports:
      - "$PORT:$PORT"
    links:
      - mysql1
    networks:
      - app-network
  mysql1:
    env_file:
      - .env
    image: mysql:5.7
    volumes:
      - ./db-data/db:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    expose:
      - "3306"
    networks:
      - app-network
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
networks:
  app-network:
    driver: bridge


